ALTER TABLE SUBMISSION ALTER COLUMN TYPE TYPE VARCHAR(255);
DROP TYPE IF EXISTS SUBMISSION_TYPE;
CREATE TYPE SUBMISSION_TYPE AS ENUM('START', 'FINISH', 'DELTA', 'BONUS');
ALTER TABLE SUBMISSION ALTER COLUMN TYPE TYPE SUBMISSION_TYPE USING (TYPE::SUBMISSION_TYPE);

DELETE FROM _VERSION;
INSERT INTO _VERSION(MAJOR, MINOR, PATCH) VALUES(1, 0, 3);