CREATE TABLE SERVER(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    DISCORD_GUILD_ID BIGINT NOT NULL
);

CREATE TABLE SERVER_MEMBER(
    SERVER_ID INT REFERENCES SERVER(ID),
    MEMBER_ID INT REFERENCES MEMBER(ID)
);

ALTER TABLE SPRINT ADD COLUMN SERVER_ID INT REFERENCES SERVER(ID);
ALTER TABLE SPRINT ADD COLUMN ACTIVE BOOLEAN DEFAULT TRUE;
ALTER TABLE SPRINT ADD COLUMN SPRINTATHON_ID INT REFERENCES SPRINTATHON(ID);
ALTER TABLE SPRINT ADD COLUMN DISCORD_CHANNEL_ID BIGINT;

ALTER TABLE SPRINTATHON ADD COLUMN SERVER_ID INT REFERENCES SERVER(ID);
ALTER TABLE SPRINTATHON ADD COLUMN ACTIVE BOOLEAN DEFAULT TRUE;
ALTER TABLE SPRINTATHON ADD COLUMN DISCORD_CHANNEL_ID BIGINT;

DELETE FROM _VERSION;
INSERT INTO _VERSION(MAJOR, MINOR, PATCH) VALUES(1, 0, 2);