CREATE TABLE IF NOT EXISTS MEMBER(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    DISCORD_USER_ID BIGINT NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'submission_type') THEN
        CREATE TYPE SUBMISSION_TYPE AS ENUM('START', 'FINISH', 'DELTA');
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS SUBMISSION(
    ID SERIAL PRIMARY KEY,
    MEMBER_ID INTEGER REFERENCES MEMBER(ID),
    WORD_COUNT INTEGER NOT NULL,
    TYPE SUBMISSION_TYPE NOT NULL
);

CREATE TABLE IF NOT EXISTS SPRINT(
    ID SERIAL PRIMARY KEY,
    START TIMESTAMP WITH TIME ZONE,
    DURATION INTERVAL
);

CREATE TABLE IF NOT EXISTS SPRINT_MEMBER(
    SPRINT_ID INTEGER REFERENCES SPRINT(ID),
    MEMBER_ID INTEGER REFERENCES MEMBER(ID)
);

CREATE TABLE IF NOT EXISTS SPRINT_SUBMISSION(
    SPRINT_ID INTEGER REFERENCES SPRINT(ID),
    SUBMISSION_ID INTEGER REFERENCES SUBMISSION(ID)
);

CREATE TABLE IF NOT EXISTS SPRINTATHON(
    ID SERIAL PRIMARY KEY,
    START TIMESTAMP WITH TIME ZONE,
    DURATION INTERVAL
);

CREATE TABLE IF NOT EXISTS SPRINTATHON_SUBMISSION(
    SPRINTATHON_ID INTEGER REFERENCES SPRINTATHON(ID),
    SUBMISSION_ID INTEGER REFERENCES SUBMISSION(ID)
);

CREATE TABLE IF NOT EXISTS _VERSION(
    MAJOR INTEGER,
    MINOR INTEGER,
    PATCH INTEGER
);

CREATE OR REPLACE VIEW VERSION AS
    SELECT _VERSION.MAJOR AS MAJOR, _VERSION.MINOR AS MINOR, _VERSION.PATCH AS PATCH FROM _VERSION LIMIT 1;